LICENSE

https://observe.atlassian.net/browse/CON-15

task: add license file

---

config_files/observe_jenkins.conf

feat: add jenkins fluent bit config

---

README.md
observe_configure_script.sh

- Remove duplicated flags
- Fix wrong endpoint URL

Update example command in the documentation

---

README.md
observe_configure_script.sh

to prepare for a later change on default hostname and authorization

remove trailing whitespaces

---

observe_configure_script.sh

add in case statement for reading observe_jenkins_path flag

fix: unset path variable

---

README.md
config_files/observe-installer.conf
config_files/telegraf.conf
observe_configure_script.sh

This update addresses the following issues:
https://observe.atlassian.net/browse/CON-79
https://observe.atlassian.net/browse/CON-379
https://observe.atlassian.net/browse/CON-454
https://observe.atlassian.net/browse/CON-203
https://observe.atlassian.net/browse/CON-368
https://observe.atlassian.net/browse/CON-455
https://observe.atlassian.net/browse/CON-475

Various installer updates

---

config_files/telegraf.conf

adds cmd_line = true to pickup process args with procstat

feat: add command line flags to procstat

---

observe_configure_script.sh

add auto start for telegraf service

fix: add sudo systemctl enable telegraf

---

test_code/AWS_MACHINES/data.tf
test_code/AWS_MACHINES/main.tf
test_code/AWS_MACHINES/variables.tf
test_code/README.md
test_code/main.tf
test_code/python_scripts/README.md
test_code/python_scripts/workflow_tasks.py

Update readme and variable definitions

chore: update readme

---

.github/workflows/AWS-EC2-Tests.yaml
.github/workflows/Azure-Compute-Tests.yaml
.github/workflows/GCP-Compute-Tests.yaml
observe_configure_script.sh

Updates telegraf install to reference new signing key for telegraf repo

fix: telegraf repo signing key

---

observe_configure_script.sh

tested with Debian 11 (Bullseye)

feat: debian support

---

test_code/BASE_INFRA/GCP/main.tf
test_code/BASE_INFRA/GCP/variables.tf
test_code/BASE_INFRA/GCP/versions.tf
test_code/GCP_MACHINES/main.tf

Moved creation of service account to base infra to avoid race conditions

fix: gcp service account for testing

---

test_code/GCP_MACHINES/main.tf

Missed reference to data resource

fix: missing data ref

---

config_files/observe-linux-host.conf
config_files/osquery.conf

this adds ip address information to the interfaces summary osquery collection.
tested on my instance using home lab vms

feat: collect ip address information

---

config_files/td-agent-bit.conf

update the default log level to error

fix: fluentbit default log level

---

.github/workflows/AWS-EC2-Tests.yaml
.github/workflows/Azure-Compute-Tests.yaml
.github/workflows/GCP-Compute-Tests.yaml
.github/workflows/Job-Clean-Up.yaml
test_code/python_scripts/workflow_tasks.py

Implements secret manager for 3 primary workflows

feat: add gcp secret manager for workfloww

---

config_files/observe-securityonion.conf

corrected hardcoding of my testing app group and datacenter variables into this fluentbit conf file

fix: hardcoded appgroup and datacenter in securityonion config

---

config_files/observe-securityonion.conf

Adds collection support for Suricata alerts when the securityonion option is selected

feat: collect suricata logs from security onion

---

observe_configure_script.sh

Uses HEAD to validate endpoint.  Also stops sending observations to Observe so we know we are receiving data from agents and not from the install script.
Tested on an ubuntu machine and letting CI test the other supported OSes.

fix: stop posting to observe in installation

---

test_code/python_scripts/fabfile.py

Adds testing to ensure that windows services are set to restart after failure.  The default behavior when we create new services is they do not do anything on failure.  We want to make sure that our install script is actually enforcing that they get restarted on failures.

tests: test windows behavior for failed services

---

test_code/AWS_MACHINES/main.tf
test_code/AWS_MACHINES/variables.tf
test_code/compute_otel_collector/main.tf
test_code/compute_otel_collector/outputs.tf
test_code/compute_otel_collector/variables.tf
test_code/compute_otel_collector/versions.tf
test_code/otel_collector_host_loginator/README.md
test_code/otel_collector_host_loginator/blunderdome/main.tf
test_code/otel_collector_host_loginator/blunderdome/user_data/aptbased.sh
test_code/otel_collector_host_loginator/blunderdome/variables.tf
test_code/otel_collector_host_loginator/blunderdome/versions.tf
test_code/otel_collector_host_loginator/main.tf
test_code/otel_collector_host_loginator/outputs.tf
test_code/otel_collector_host_loginator/user_data/aptbased.sh
test_code/otel_collector_host_loginator/variables.tf
test_code/otel_collector_host_loginator/versions.tf
test_code/user_data/aptbased.sh

This creates a vm using otel collector that has log gen utility and stress utility to generate logs and metrics based on cronjob schedule

feat: add log generator and stress vm template

---

uninstall.sh

Adds uninstall script for linux agents.  Tested on all of our supported OSes (i.e. the machines in the test file in this repo).

feat: add uninstall script

---

observe_configure_script.sh

fix: centos releasever

---

.github/CODEOWNERS
README.md
config_files/observe-installer.conf
config_files/observe-jenkins.conf
config_files/observe-linux-host.conf
config_files/observe-securityonion.conf
config_files/parsers-observe.conf
other_configs/fluent_monitoring/README.md
other_configs/fluent_monitoring/observe-monitoring-all-platforms.conf
other_configs/fluent_monitoring/observe-monitoring-linux-only.conf

Creates manually deployable set of configs to support health monitoring of fluentbit agent

feat: cs-376 add manual fluent-bit monitoring configs

---

other_configs/fluent_monitoring/README.md
other_configs/fluent_monitoring/mask.lua
other_configs/fluent_monitoring/observe-monitoring-all-platforms.conf

Lua filter for masking second half of token

feat: CS-420 replace sensitive part of token with asterisks

---

observe_configure_script.sh

Adds alma linux to rhel/centos OS

feat: add alma linux to observe config script

---

.gitignore
README.md
config_files/osquery.conf
observe_configure_script.sh

Added shell_history_enable option to enable collecting OS Query shell_history.

feat(osquery): Added shell_history_enable option to enable collecting OS Query shell_history

---

README.md
observe_configure_script.sh

Mark repo as deprecated and point people towards quickstart

feat: OB-32127 deprecate host monitoring
